services:
  - type: web
    name: digit-classifier-backend
    runtime: python3
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python app.py"
    plan: free
    healthCheckPath: /test
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: digit-classifier-backend
          property: port 